name: Deploy to Production

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
    
jobs:

  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    env:
        AWS_REGION: ap-south-1                      
        AWS_ACCOUNT_ID: 330552994974             
        ECR_REPOSITORY: backend-with-go/simplebank         
        IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check Docker version
        run: docker --version

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.31.0'
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::330552994974:role/GitHubActionsECRPushRole
          aws-region:  ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        
      - name: Load Secrets and Save to app.env
        run: |
          aws secretsmanager get-secret-value --secret-id prod/SimpleBank/Postgres --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

          echo "Building Docker image..."
          docker build -t $IMAGE_URI:$IMAGE_TAG -t latest .

          echo "Pushing image with tag $IMAGE_TAG..."
          docker push -a $IMAGE_URI

          echo "Tagging as latest..."
          docker tag $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest
          docker push $IMAGE_URI:latest
      
      - name: Print image URI
        run: |
          echo "Docker image pushed: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name simple-bank --region ap-south-1
         
      - name: Deploy Image to Amazon EKS
        run: |
          kubectl apply -f eks/aws-auth.yaml
          kubectl apply -f eks/deployment.yaml
          kubectl apply -f eks/service.yaml
          kubectl apply -f eks/issuer.yaml
          kubectl apply -f eks/ingress.yaml